version: '2.0'
services:
  mtprotoproxy:
    image: ghcr.io/dealenx/mtprotoproxy:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MTPROTO_PORT=${MTPROTO_PORT:-443}
      - MTPROTO_SECRET=${MTPROTO_SECRET:-90f1cdecf45ef2210411b4eb154fad0c}
      - MTPROTO_TLS_DOMAIN=${MTPROTO_TLS_DOMAIN:-}
      - MTPROTO_AD_TAG=${MTPROTO_AD_TAG:-}
      - MTPROTO_MODES=${MTPROTO_MODES:-}
    volumes:
        - /etc/localtime:/etc/localtime:ro
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "10m"
#    mem_limit: 1024m
